### ISSUE TITLE
[Suggestions] Province name suggestions

### ISSUE THREAD

**Issue by ese-khan** [escalonn/sed2#2]
1624: Hund (modern-day name of Udahandapura; started appearing in Muslim sources during CK2 period)
1628: Kashmir (I think we all know where that is!)
1687: Nashik (modern-day name of Nasikya)

**Comment by escalonn** [comment]
there is some confusion whether Udabhandapura/Udabhanda, city of the Shahis, is the place now called Hund or the place now called Muzaffarabad. but the former does seem to have the better of it
for 1687, you must mean some other province ID, that one is Prayag/Allahabad

**Comment by ese-khan** [comment]
The location issue is present in many cities, so that's kind of a given haha. The bigger issue with Muzaffarabad, I would say, is its historicity. AFAIK it appeared much later than Hund/Waihind, etc. did, after the CK2 era.

As for Allahabad, I forgot that we recycled that ID to elsewhere in India. It can wait until the next HIP release.

**Comment by escalonn** [comment]
yeah sed is still tracking master not beta.

**Comment by escalonn** [comment]
incorporated
